[client] Indexed row support projection
alibaba/fluss pull request #151
Opened 2024-12-09 13:00 UTC by swuferhong

### Purpose

Linked issue:  https://github.com/alibaba/fluss/issues/150

Even if Fluss only support projection push down to server for log format as ARROW. However, INDEXED format also need to support projection push down in client side. This pr is aims to fix this bug.

### Tests

### API and Format

### Documentation

2024-12-23 15:11 UTC, wuchong requested changes
Please add connector tests.

2024-12-23 15:11 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/scanner/log/LogFetcher.java
> +    private boolean projectPushDownEnable() {
`projectionPushDowned`

2024-12-23 15:11 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/scanner/log/RemoteCompletedFetch.java
> +    protected FieldGetter[] buildFieldGetters() {
We have reused the fieldGetters in `LogRecordReadContext` to avoid re-construction. See https://github.com/alibaba/fluss/commit/376ee8707c2ec5f82200af857a80bed32f72d4d6

Please move this logic into `LogRecordReadContext` as well and rename the  method to `getProjectedFieldGetters`

2024-12-24 06:17 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/scanner/log/LogFetcher.java
> +    private boolean projectPushDownEnable() {
Done!

2024-12-24 07:41 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/scanner/log/RemoteCompletedFetch.java
> +    protected FieldGetter[] buildFieldGetters() {
Done!

2024-12-24 08:12 UTC, swuferhong commented
> Please add connector tests.

Done! comments all addressed. Pr ready.

2024-12-24 08:26 UTC, swuferhong commented
@wuchong  Comments addressed. CI passed

2024-12-24 16:23 UTC, wuchong commented
@swuferhong I refactored the code and only project the row once to reduce CPU costs. Please have a look.

2024-12-25 00:58 UTC, swuferhong commented
> @swuferhong I refactored the code and only project the row once to reduce CPU costs. Please have a look.

LGTM +1

2024-12-25 02:37 UTC, merged