[server] Cdc log visible only when the data already flush to rocksDb from preWriteBuffer
alibaba/fluss pull request #179
Opened 2024-12-13 07:20 UTC by swuferhong

### Purpose

This pr is aims to fix the visibility of the CDC log, it should only become visible after the KV data has been flushed to RocksDb.

Linked issue: https://github.com/alibaba/fluss/issues/134

### Tests

### API and Format

### Documentation

2025-02-27 10:17 UTC, wuchong reviewed
We need to add a test to reproduce the problem. Maybe add a test in `ReplicaManagerTest` to verify the high-watermark of the given record is must advanced if the given record can be read in kv.

2025-02-27 10:17 UTC, wuchong commented on fluss-client/src/test/java/com/alibaba/fluss/client/admin/ClientToServerITCaseUtils.java
> +public class ClientToServerITCaseUtils {
This does not seem to be used.

2025-02-27 10:17 UTC, wuchong commented on fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java
> +            mayFlushKv(newAckedLogEndOffset.getMessageOffset());
maybe we can simplify flush kv first, and then update high-watermark? Our purpose is just make KV ready before log is available. This can avoid introducing additional variable `ackedLogEndOffsetMetadata` (it is quite complex if we need to handle the restore of the new variable).

2025-03-03 01:59 UTC, swuferhong commented on fluss-client/src/test/java/com/alibaba/fluss/client/admin/ClientToServerITCaseUtils.java
> +public class ClientToServerITCaseUtils {
Done!

2025-03-03 02:39 UTC, swuferhong commented on fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java
> +            mayFlushKv(newAckedLogEndOffset.getMessageOffset());
Done!

2025-03-03 06:18 UTC, swuferhong commented
@wuchong comments addressed.

2025-03-03 06:32 UTC, wuchong requested changes

2025-03-03 06:32 UTC, wuchong commented on fluss-server/src/main/java/com/alibaba/fluss/server/log/LogTablet.java
> -                updateHighWatermarkMetadata(newHighWatermark);
This makes the `maybeIncrementHighWatermark` very confusing and very error-prone. 

1. The `maybeIncrementHighWatermark` actually won't update the highwatermark underlying, which is inconsistent with the method name (even the Javadoc clarifies, but if a method name needs Javadoc to explain for it, the method is not a good design).
2. The watermark updates become non-atomic as it is in two different locks.

2025-03-03 06:32 UTC, wuchong commented on fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java
>              mayFlushKv(newHighWatermark.getMessageOffset());
Why not simplify move the `mayFlushKv` before `leaderLog.maybeIncrementHighWatermark`?

2025-03-03 06:55 UTC, swuferhong commented on fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java
>              mayFlushKv(newHighWatermark.getMessageOffset());
Initially, I thought that the `flushKV` and `updateHighWatermark` operations should only be completed after the `newHighWatermark` is confirmed to be applied. However, in fact, the flushKV logic already includes conditions to skip actions when `newHighWatermark` is less than the current `highWatermark`.

2025-03-03 06:55 UTC, swuferhong commented on fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java
>              mayFlushKv(newHighWatermark.getMessageOffset());
Done!

2025-03-03 08:44 UTC, wuchong commented on fluss-server/src/test/java/com/alibaba/fluss/server/replica/ReplicaManagerTest.java
> +                    1,
this test can reproduce the problem, because it only has one replia and ack=1, so after executing `replicaManager.putRecordsToKv`, the watermark has been advanced, and kv data has been flushed, thus the following test is always success without any changes to the source code.

2025-03-04 02:39 UTC, swuferhong commented on fluss-server/src/test/java/com/alibaba/fluss/server/replica/ReplicaManagerTest.java
> +                    1,
Yes, I switched to a multi-thread way to validate this issue. In the new test, if `highWatermarkUpdateTimestamp` is less than `lastTimestampForNullValue` even once, it indicates that the CDC log visibility is earlier than the KV. Specifically, `highWatermarkUpdateTimestamp` is later than the actual `highWatermarkUpdate` time, and `lastTimestampForNullValue` is earlier than the collected time, which is intended to eliminate influence of collecting. Pr ready.

2025-03-04 02:40 UTC, swuferhong commented on fluss-server/src/test/java/com/alibaba/fluss/server/replica/ReplicaManagerTest.java
> +                    1,
In my local env, if you revert the change, the test will always failed.

2025-03-04 06:44 UTC, swuferhong commented
@wuchong comments addressed.

2025-03-05 14:07 UTC, wuchong commented on fluss-server/src/test/java/com/alibaba/fluss/server/replica/ReplicaManagerTest.java
> +                                if (replica.getLogHighWatermark() == count + 1) {
The test is unstable as the while loop may become a dead loop.

![image](https://github.com/user-attachments/assets/f9470fef-36d0-43df-9822-0a467622aff0)

2025-03-06 03:12 UTC, swuferhong commented on fluss-server/src/test/java/com/alibaba/fluss/server/replica/ReplicaManagerTest.java
> +                                if (replica.getLogHighWatermark() == count + 1) {
Done! Change `==` to `>=` to avoid dead loop

2025-03-06 03:47 UTC, wuchong approved these changes

2025-03-06 03:49 UTC, merged