[kv] Support index lookup for primary key table
alibaba/fluss pull request #222
Opened 2024-12-18 13:52 UTC by swuferhong

### Purpose

Linked issue: https://github.com/alibaba/fluss/issues/65

Index lookup is a feature that exposes lookup capabilities built on top of secondary indexes. By using secondary indexes, the required data can be located quickly, which can be utilized in conjunction with Flink to implement delta joins.
The purpose of this PR is to provide index lookup for kv tables. The implementation approach is to define the primary key of the kv storage as "secondary keys + primary key", and set the bucket key to the secondary keys. This way, when looking up data through the secondary keys, the corresponding bucket and server can be quickly identified, providing efficient point query capabilities.

### Tests

### API and Format

### Documentation

2024-12-21 13:27 UTC, wuchong requested changes
I think our current index is not a general index, it is just a prefix of primary key index. So, actually, it is just a prefix scan/lookup for the prefix of primary key (the prefix should include bucket key). I don't want to call this `indexLookup` because it occupies the API for future possible index (index on arbitrary columns). 

How about changing the API into `prefixLookup`? The parameter `key` should be the prefix of primary key and must include bucket key. For DDL, we don't need to introduce new options `table.index.keys`, we can just continue to use `bucket.key`. 

As we don't have force checks for bucket key is a prefix of primary key. We have to add some best practices for Delta Join cases in the future documentation. For tables used for DeltaJoin queries, the best practice is putting columns of bucket key before other columns in the definition of primary key. Otherwise, the `prefixLookup` doesn't work when the parameter key only contains bucket join. For example, given a primary key table `orders` with schema `user_id, item_id, order_id, col1, col2, col3` (`order_id` can be used as primary key as it is unique). If the join key is `(user_id, item_id)`, the primary key of the table must be set to `user_id, item_id, order_id` and bucket key to `user_id, item_id`. The `prefixLookup` will not work if the primary key is set to `order_id, user_id, item_id`, because the join key is not a prefix of primary key.

2024-12-21 13:27 UTC, wuchong commented on website/docs/maintenance/monitor-metrics.md
> +      <td>The number of limit scn requests to scan records with limit from this table per second.</td>
scn -> scan?

2024-12-21 13:27 UTC, wuchong commented on website/docs/maintenance/monitor-metrics.md
> +      <td>The number of failed limit scn requests to scan records with limit from this table per second.</td>
ditto

2024-12-21 13:27 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/AbstractLookup.java
> +    public abstract LookupType lookupType();
> Class 'LookupType' is exposed outside its defined visibility scope 

Make `LookupType` public.

2024-12-21 13:27 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/AbstractLookupBatch.java
> +public abstract class AbstractLookupBatch {
This is only used by `IndexLookupBatch`, we don't need this abstraction.

2024-12-21 13:27 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/AbstractLookup.java
> +    public abstract CompletableFuture<List<byte[]>> future();
This is strange and inefficient that `Lookup` returns a List of result. We can introduce a generic type `T` to `AbstractLookup` and allows `Lookup` and `IndexLookup` to define their own return type. 

```java
public abstract class AbstractLookup<T> {

    ...

    public abstract CompletableFuture<T> future();
}

public class Lookup extends AbstractLookup<byte[]> {
  ...
}

public class IndexLookup extends AbstractLookup<List<byte[]>> {
  ...
}
```

2024-12-21 13:27 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/IndexLookup.java
> +    private final int destination;
why `IndexLookup` has to bound a `destination` at the beginning?

2024-12-21 13:27 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/IndexLookup.java
> +    private final int bucketId;
This should be the same with `Lookup` that has a `TableBucket` member variable, and we can move the `TableBucket` to the parent `AbstractLookup`.

2024-12-21 13:27 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/IndexLookup.java
> +    private final String indexName;
Remove it as not used.

2024-12-21 13:27 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupClient.java
> +        // TODO index lookup support partition table.
create an issue for this?

2024-12-21 13:27 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupClient.java
> +        int leader = metadataUpdater.leaderFor(new TableBucket(tableId, bucketId));
leader should be determined when sending.

2024-12-21 13:27 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupQueue.java
> +    private final ArrayBlockingQueue<AbstractLookup> indexLookupQueue;
We should unify the queue otherwise the abstraction of `AbstractLookup` is meaningless. This can also simplify things a lot. Such as:

```java
// buffering both the Lookup and IndexLookup requests
private final ArrayBlockingQueue<AbstractLookup> lookupQueue;

void appendLookup(AbstractLookup lookup){
   ...
   lookupQueue.put(lookup);
   ...
}

List<AbstractLookup> drain();

List<AbstractLookup> drainAll();
```


We don't need to distinguish the lookup type when draining. We can dispatch the specific lookups when sending.  See comments in `LookupSender`.

2024-12-21 13:27 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/table/Table.java
> +    CompletableFuture<LookupResult> indexLookup(String indexName, InternalRow indexKey);
Use different return type for `indexLookup` and `lookup`. Lookup should have determined single row result.

2024-12-21 13:27 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupSender.java
> +        }
Simplify this into:


```java
    private void runOnce(boolean drainAll) throws Exception {
        List<AbstractLookup> lookups = drainAll ? lookupQueue.drainAll() : lookupQueue.drain();
        sendLookups(lookups);
    }

   private void sendLookups(List<AbstractLookup> lookups) {
        if (lookups.isEmpty()) {
            return;
        }
        // group by <leader&type, lookup batches> to lookup batches
        Map<Tuple2<Integer, LookupType>, List<AbstractLookup>> lookupBatches = groupByLeaderAndType(lookups);
        // now, send the batches
        lookupBatches.forEach(this::sendLookupRequests);
    }
```

`sendLookupRequests` should invoke different RPC methods depends on the `LookupType`. 

Here, we drain `Lookup` and `IndexLookup` together from an unique queue, this shouldn't be a problem for batching, because usually, there is only one kind of lookup for a Fluss connection.

2024-12-21 13:27 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupSender.java
> +                    error.formatErrMsg());
Just log error for a summary, don't need to log for every bucket.

2024-12-21 13:27 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/table/writer/UpsertWriter.java
> +            @Nullable int[] indexKeyIndex) {
We don't need this parameter to build the bucket key encoder. The bucket key information can be obtained from the `TableDescriptor` directly.

2024-12-21 13:27 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/table/FlussTable.java
> +        int bucketId = HashBucketAssigner.bucketForRowKey(indexKeyBytes, numBuckets);
Should consider `lakeTableBucketAssigner`, see the implementation of `CompletableFuture<LookupResult> lookup(InternalRow key)`.

2024-12-21 13:27 UTC, wuchong commented on fluss-common/src/main/java/com/alibaba/fluss/metadata/TableDescriptor.java
> +            throw new InvalidIndexKeysException(
Just throw `IllegalArgumentException`. `ApiException` is used for communication between server and client, and will erase all the exception stack. `TableDescriptor` is a client API and erasing the exception stack is very un-friendly for users.

2024-12-21 13:27 UTC, wuchong commented on fluss-common/src/main/java/com/alibaba/fluss/utils/BytesUtils.java
> +            if (bytes1[i] != bytes2[i]) {
If `bytes2.length` < `bytes1.length`, here will throw `IndexOutOfBoundsException`. I don't think we need a general prefix equals of 2 byte arrays. We only need to make sure the `bytes2` is a prefix of `bytes1`, so an array length check is needed and more efficient at the beginning. After that, we can't have the util in common `BytesUtils`, move it into `RocksDBKv` and add javadoc to describe the compare logic.

2024-12-21 13:27 UTC, wuchong commented on fluss-common/src/main/java/com/alibaba/fluss/utils/BytesUtils.java
> +        for (int i = 0; i < bytes1.length; i++) {
This is very inefficient to compare arrays byte by byte. Java9 provides a more efficient way [`Arrays.compare(compare(byte[] a, int aFromIndex, int aToIndex, byte[] b, int bFromIndex, int bToIndex))`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Arrays.html#compare(byte%5B%5D,int,int,byte%5B%5D,int,int)), underlying it leverages SIMD instructions. 

As it is only supported since Java9, we can implement it in a similar way like `Crc32C`. 

We can create a follow-up issue to support this. Micro benchmarks is needed of course.

2024-12-21 13:27 UTC, wuchong commented on fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/catalog/FlinkTableFactory.java
> +                                FlinkConnectorOptions.INDEX_LOOKUP_KEY,
it is already included in `FlinkConnectorOptions.TABLE_OPTIONS`.

2024-12-21 13:27 UTC, wuchong commented on fluss-rpc/src/main/proto/FlussApi.proto
> +message PbIndexLookupRespForKey {
make it more general, `PbValueList`?

2024-12-21 13:27 UTC, wuchong commented on fluss-rpc/src/main/proto/FlussApi.proto
> +  repeated PbIndexLookupRespForKey keys_resp = 3;
`repeated PbValueList value_lists = 3;`

2024-12-21 13:27 UTC, wuchong commented on fluss-rpc/src/main/proto/FlussApi.proto
> +message PbIndexData {
can be removed?

2024-12-21 13:27 UTC, wuchong commented on fluss-server/src/main/java/com/alibaba/fluss/server/kv/rocksdb/RocksDBKv.java
> +            iterator.close();
add `close()` for `limitScan` as well?

2024-12-21 13:27 UTC, wuchong commented on fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java
> +                        // the index key is serialized by index name + index key fields, see
I think this is not applicable anymore.

2024-12-21 13:27 UTC, wuchong commented on fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java
> +            respForBucket.setBucketId(tb.getBucket());
set partition id as well .

2024-12-21 13:27 UTC, wuchong commented on fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java
> +    public void indexLookup(
`indexLookup` -> `indexLookups`

and rename `multiLookupValues` to `lookups`

2024-12-21 13:27 UTC, wuchong commented on fluss-server/src/test/java/com/alibaba/fluss/server/replica/ReplicaManagerTest.java
> +        // TODO
missing implementation

2024-12-21 13:27 UTC, wuchong commented on fluss-server/src/test/java/com/alibaba/fluss/server/testutils/KvTestUtils.java
> +        checkArgument(indexLookupResponse.getBucketsRespsCount() == 1);
do not use `checkArgument` for assertion. Use `assertThat` instead!

2024-12-21 13:27 UTC, wuchong commented on fluss-server/src/test/java/com/alibaba/fluss/server/tablet/TabletServiceITCase.java
> +                                                                new Object[] {
code is not readable, reformat it.

2024-12-24 09:28 UTC, swuferhong commented on website/docs/maintenance/monitor-metrics.md
> +      <td>The number of failed limit scn requests to scan records with limit from this table per second.</td>
Done!

2024-12-24 09:31 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/AbstractLookup.java
> +    public abstract LookupType lookupType();
Done!

2024-12-24 09:34 UTC, swuferhong commented on fluss-server/src/main/java/com/alibaba/fluss/server/kv/rocksdb/RocksDBKv.java
> +            iterator.close();
Done!

2024-12-24 09:35 UTC, swuferhong commented on fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java
> +                        // the index key is serialized by index name + index key fields, see
Done!

2024-12-24 09:43 UTC, swuferhong commented on fluss-rpc/src/main/proto/FlussApi.proto
> +message PbIndexLookupRespForKey {
Done!

2024-12-24 09:43 UTC, swuferhong commented on fluss-rpc/src/main/proto/FlussApi.proto
> +  repeated PbIndexLookupRespForKey keys_resp = 3;
Done!

2024-12-24 09:43 UTC, swuferhong commented on fluss-rpc/src/main/proto/FlussApi.proto
> +message PbIndexData {
Done!

2024-12-24 11:20 UTC, swuferhong commented on fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java
> +            respForBucket.setBucketId(tb.getBucket());
Done!

2024-12-24 11:22 UTC, swuferhong commented on fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java
> +    public void indexLookup(
Done!

2024-12-25 01:51 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupSender.java
> +                    error.formatErrMsg());
Done!

2024-12-25 03:41 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupSender.java
> +        }
Done!

2024-12-25 03:42 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupQueue.java
> +    private final ArrayBlockingQueue<AbstractLookup> indexLookupQueue;
Done!

2024-12-25 03:42 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupClient.java
> +        int leader = metadataUpdater.leaderFor(new TableBucket(tableId, bucketId));
Done!

2024-12-25 03:42 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/IndexLookup.java
> +    private final String indexName;
Done!

2024-12-25 03:43 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/IndexLookup.java
> +    private final int bucketId;
Done!

2024-12-25 03:44 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/IndexLookup.java
> +    private final int destination;
The old code need this to broadcast to different server, but current code don't need. this can be move to `LookupSender`.

2024-12-25 03:44 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/AbstractLookup.java
> +    public abstract CompletableFuture<List<byte[]>> future();
Done!

2024-12-25 03:57 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/AbstractLookupBatch.java
> +public abstract class AbstractLookupBatch {
Done!

2024-12-25 03:59 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupClient.java
> +        // TODO index lookup support partition table.
Done, issue link: https://github.com/alibaba/fluss/issues/266

2024-12-25 04:11 UTC, swuferhong commented on fluss-server/src/test/java/com/alibaba/fluss/server/testutils/KvTestUtils.java
> +        checkArgument(indexLookupResponse.getBucketsRespsCount() == 1);
Done!

2024-12-25 07:59 UTC, swuferhong commented on fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/catalog/FlinkTableFactory.java
> +                                FlinkConnectorOptions.INDEX_LOOKUP_KEY,
Done!  INDEX_LOOKUP_KEY already removed.

2024-12-26 03:03 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/table/Table.java
> +    CompletableFuture<LookupResult> indexLookup(String indexName, InternalRow indexKey);
Done!

2024-12-26 03:15 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/table/writer/UpsertWriter.java
> +            @Nullable int[] indexKeyIndex) {
Done!

2024-12-26 03:15 UTC, swuferhong commented on fluss-client/src/main/java/com/alibaba/fluss/client/table/FlussTable.java
> +        int bucketId = HashBucketAssigner.bucketForRowKey(indexKeyBytes, numBuckets);
Done!

2024-12-26 03:15 UTC, swuferhong commented on fluss-common/src/main/java/com/alibaba/fluss/metadata/TableDescriptor.java
> +            throw new InvalidIndexKeysException(
This logic is removed.

2024-12-26 03:33 UTC, swuferhong commented on fluss-common/src/main/java/com/alibaba/fluss/utils/BytesUtils.java
> +            if (bytes1[i] != bytes2[i]) {
Done!

2024-12-26 03:54 UTC, swuferhong commented on fluss-common/src/main/java/com/alibaba/fluss/utils/BytesUtils.java
> +        for (int i = 0; i < bytes1.length; i++) {
Done, I have open a  issue to trace this: https://github.com/alibaba/fluss/issues/271

2024-12-26 04:18 UTC, swuferhong commented on fluss-server/src/test/java/com/alibaba/fluss/server/tablet/TabletServiceITCase.java
> +                                                                new Object[] {
Done!

2024-12-26 07:20 UTC, swuferhong commented on fluss-server/src/test/java/com/alibaba/fluss/server/replica/ReplicaManagerTest.java
> +        // TODO
Done!

2024-12-26 08:18 UTC, swuferhong commented
@wuchong comments addressed. PR ready

2025-01-02 16:07 UTC, wuchong reviewed
I will push a commit to address the comments.

2025-01-02 16:07 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupQueue.java
> +            AbstractLookup<?> lookup = lookupQueue.poll(300, TimeUnit.MILLISECONDS);
The original implementation of `drain()` is much more efficient which avoids a lot of `poll`s.

2025-01-02 16:07 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupResult.java
> +    private final InternalRow row;
Missing `@Nullable`.

2025-01-02 16:07 UTC, wuchong commented on fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/lookup/LookupNormalizer.java
> +        }
This should be moved out of the utility. 
1. A method should rely on external elements as little as possible, to make the method can be easily unit tested. A utility relying on an RPC call is hard to be tested. 
2. It's too heavy to perform a RPC call only to get a bucket key information. Actually, the bucket key information can be obtained from table options from TableFactory.

2025-01-02 16:07 UTC, wuchong commented on fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/lookup/LookupNormalizer.java
> +            return createLookupNormalizer(lookupKeys, primaryKeys, schema, LookupType.LOOKUP);
primary key lookup should have higher priority, otherwise, all the primary key lookup will become prefix lookup.

2025-01-02 16:07 UTC, wuchong commented on fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java
> +                if (!replica.supportPrefixLookup()) {
As the prefix lookup request already arrives to the bucket/replica, we don't need to fail the request, just perform the prefix lookup and return what is returned. The "supportPrefixLookup" is more like a client side property that the client need to determine the bucket id from the requested key.

2025-01-02 16:07 UTC, wuchong commented on fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java
> +                    List<byte[]> resultForPerKey = new ArrayList<>(replica.prefixLookup(prefixKey));
Why do a deep copy?

2025-01-02 16:07 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupQueue.java
> +            AbstractLookup<?> lookup = lookupQueue.poll(300, TimeUnit.MILLISECONDS);
This is not efficient to get lock for every element, and this may exceed the max wait time (`CLIENT_LOOKUP_BATCH_TIMEOUT`).

2025-01-02 16:07 UTC, wuchong commented on fluss-client/src/main/java/com/alibaba/fluss/client/table/writer/UpsertWriter.java
> +        byte[] bucketKey = bucketKeyEncoder.encode(row);
avoid to encode twice for common cases (default bucket key).

2025-01-03 03:59 UTC, swuferhong commented on fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/lookup/LookupNormalizer.java
> +        }
> This should be moved out of the utility.
> 
> 1. A method should rely on external elements as little as possible, to make the method can be easily unit tested. A utility relying on an RPC call is hard to be tested.
> 2. It's too heavy to perform a RPC call only to get a bucket key information. Actually, the bucket key information can be obtained from table options from TableFactory.

Ok, I will avoid to do that in the future.

2025-01-03 06:04 UTC, swuferhong commented
@swuferhong LGTM +1， and CI passed.

2025-01-03 06:04 UTC, swuferhong commented
@wuchong LGTM +1, and CI passed.

2025-01-03 07:11 UTC, merged