[kv] Support first row merge engine
alibaba/fluss pull request #240
Opened 2024-12-20 11:36 UTC by luoyuxia

### Purpose

Linked issue: close #212

Introduce first row merge engine for primary key table

### Tests
FlussTableITCase#testFirstRowMergeEngine
FlinkTableSinkITCase#testFirstRowMergeEngine

### API and Format

N/A

### Documentation
todo:

2024-12-21 14:12 UTC, wuchong requested changes
We need add validations for `FlinkTableSink` that `first_row` table doesn't supports UPDATE/DELETE and partial-update! And add tests to verify that.

2024-12-21 14:12 UTC, wuchong commented on fluss-client/src/test/java/com/alibaba/fluss/client/table/FlussTableITCase.java
> +        int rowNum = 3;
`duplicateNum`

2024-12-21 14:12 UTC, wuchong commented on fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/catalog/FlinkTableFactory.java
> +                                .noDefaultValue()));
create a local variable for this, to make the code more readable.

2024-12-21 14:12 UTC, wuchong commented on fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSinkITCase.java
> +                tEnv.executeSql("insert into first_row_sink select * from first_row_source")
Is this used for verifying append-only strema? If yes, 

1. add the motivation comment, `insert from first_row_source to first_row_sink` is a useless comment as we all know from the code. 
2. the sink table name would be better to `log_sink` 
3. read from the `log_sink` and verify the result.

2024-12-23 03:51 UTC, luoyuxia commented
@wuchong Comments addressed...

2024-12-23 12:26 UTC, wuchong commented on fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSink.java
> +                            "Table %s is with merge engine '%s'. Table with '%s' merge engine doesn't support DELETE and UPDATE statements.",
Table xxx uses the 'first_row' merge engine, which does not support DELETE or UPDATE statements.

2024-12-23 12:26 UTC, wuchong commented on fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSinkITCase.java
> +    void testUnsupportedDeleteAndUpdateStmtOnFirstRowMergeEngine() {
verify partial update as well!

2024-12-23 12:26 UTC, wuchong commented on fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/catalog/FlinkTableFactory.java
> +                                        .noDefaultValue());
reuse the definition?

2024-12-24 04:23 UTC, wwj6591812 commented on fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSink.java
> +        if (mergeEngine != null && mergeEngine == ConfigOptions.MergeEngine.FIRST_ROW) {
May "mergeEngine != null" can deleted?

2024-12-24 04:23 UTC, wwj6591812 commented on fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/FlinkTableSource.java
> +                if (mergeEngine == ConfigOptions.MergeEngine.FIRST_ROW) {
ConfigOptions.MergeEngine.FIRST_ROW.equals(mergeEngine)

2024-12-24 09:37 UTC, luoyuxia commented
@wuchong Comments addressed again...

2025-01-05 14:47 UTC, wuchong approved these changes
LGTM. @luoyuxia I appended a commit to improve the config operations: 

1. Move `MergeEngine` out of `ConfigOptions`, as it is very widely used in the code base, just like `KvFormat`. 
2. use `toFlinkOption` for quick/easy conversion from Fluss ConfigOption to Flink ConfigOption, avoid duplicate definition in `FlinkTableFactory`.

2025-01-05 15:52 UTC, wuchong commented
The CI is passed. I will merge it... 

@luoyuxia please check the commit I appended.

2025-01-05 15:52 UTC, wuchong commented
The CI is passed. I will merge it... 

@luoyuxia please check the commit I appended.

2025-01-05 15:55 UTC, merged